# Generated by Django 6.0.1 on 2026-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tech',
            field=models.JSONField(default=list),
        ),
    ]
